=== Davidrc02/1-DAW-20_21/Lenguaje de Marcas/XML/cristianPrueba.dtd
<!ELEMENT ies (modulos)>
<!ELEMENT modulos (modulo+)>
<!ELEMENT modulo (profesor,asignaturas)>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT asignaturas (asig1,horas,asig2,horas,asig3,horas)>
<!ELEMENT asig1 (#PCDATA)>
<!ELEMENT horas (#PCDATA)>
<!ELEMENT asig2 (#PCDATA)>
<!ELEMENT asig3 (#PCDATA)>

=== Davidrc02/1-DAW-20_21/Lenguaje de Marcas/XML/cristianPrueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ies SYSTEM "cristianPrueba.dtd">
<ies>
    <modulos>
        <modulo>
            <profesor>MJ</profesor>
            <asignaturas>
                <asig1>LM</asig1>
                    <horas>5</horas>
                <asig2>BBDD</asig2>
                    <horas>5</horas>
                <asig3>PROG</asig3>
                    <horas>5</horas>
            </asignaturas>
        </modulo>
        <modulo>
            <profesor>ANA</profesor>
            <asignaturas>
                <asig1>LM</asig1>
                    <horas>5</horas>
                <asig2>BBDD</asig2>
                    <horas>5</horas>
                <asig3>PROG</asig3>
                    <horas>5</horas>
            </asignaturas>
        </modulo>
    </modulos>
</ies>
