=== Davidrc02/1-DAW-20_21/Lenguaje de Marcas/XML/Boletin8/Ejercicio6/ejercicio6.dtd
<!ELEMENT pedidos (pedido*)>
<!ELEMENT pedido (cliente, empleado, correo, fechapedido, codigopostalenvio, codigopostalpago, producto*)>
<!ELEMENT cliente (nombre, direccionenvio, direccionpago)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccionenvio (#PCDATA)>
<!ELEMENT direccionpago (#PCDATA)>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT fechapedido (#PCDATA)>
<!ELEMENT codigopostalenvio (#PCDATA)>
<!ELEMENT codigopostalpago (#PCDATA)>
<!ELEMENT producto (tipo, electrica?, codigoproducto, precio)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT electrica (#PCDATA)>
<!ELEMENT codigoproducto (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== Davidrc02/1-DAW-20_21/Lenguaje de Marcas/XML/Boletin8/Ejercicio6/ejercicio6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "ejercicio6.dtd">
<pedidos>
    <pedido>
        <cliente>
            <nombre>Roberto Movilla</nombre>
            <direccionenvio>Plaza de la Duquesa 12, Albacete</direccionenvio>
            <direccionpago>General Ricardos 56, Madrid</direccionpago>
        </cliente>
        <empleado>Manuel Jiménez</empleado>

        <correo>
        Hola, necesito una cortadora de césped para mi jardín
        de esas que anuncian en oferta, me gustaría que fuera
        uno de esos modelos eléctricos, pues las de gasolina
        contaminan mucho. Me llamo Roberto Movilla, la 
        cortadora la tendrán que enviar a Albacete, la 
        dirección es Plaza de la Duquesa 12, la recogerá mi
        esposa que se llama Alicia Abad. Ahora que lo pienso
        también necesitaré 3 podadoras para los setos.
        Les paso mi dirección de aquí para lo referente
        al pago, es General Ricardos 56, aquí en Madrid.
        Es urgente, por favor, el césped está muy alto.
        </correo>

        <fechapedido>20/10/2010</fechapedido>
        <codigopostalenvio>05020</codigopostalenvio>
        <codigopostalpago>28055</codigopostalpago>

        <producto>
            <tipo>Cortadora</tipo>
            <electrica>Es eléctrica</electrica>
            <codigoproducto>872-AA</codigoproducto>
            <precio>148.95</precio>
        </producto>

        <producto>
            <tipo>Podadora</tipo>
            <codigoproducto>Podadora: 926-FH</codigoproducto>
            <precio>Precio podadora: 7.98</precio>
        </producto> 

    </pedido>
</pedidos>
